version: "3.9"

services:
  backend:
    build: ./backend
    container_name: math-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build: ./frontend
    container_name: math-frontend
    ports:
      - "3000:80"
    restart: always
